name: dotnet package
on: [ push ]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
#        uses: actions/setup-dotnet@v4
#      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
#        run: dotnet build ImmersiveCrosshair.sln
      - name: Test with the dotnet CLI
        run: dotnet test